superpoint:
  max_keypoints: 600
  keypoint_threshold: 0.005
  remove_borders: 4
  input_tensor_names:
    - "input"
  output_tensor_names:
    - "scores"
    - "descriptors"
  onnx_file: "superpoint_v1_sim_int32.onnx"
  engine_file: "superpoint_v1_sim_int32.engine"
  dla_core: -1

superglue:
  image_width: 1241
  image_height: 376
  input_tensor_names:
    - "keypoints_0"
    - "scores_0"
    - "descriptors_0"
    - "keypoints_1"
    - "scores_1"
    - "descriptors_1"
  output_tensor_names:
    - "scores"
  onnx_file: "superglue_outdoor_sim_int32.onnx"
  engine_file: "superglue_outdoor_sim_int32.engine"
  dla_core: -1
